### ISSUE TITLE
Feature request: Ability to use keyboard letters to select notes

### ISSUE THREAD

**Issue by Cezille07** [walfie/ac-tune-maker#53]
Hi! I love this app, and having fun recreating my favorite songs on it for ACNH.

However, pressing the up and down arrows hundreds of times while tweaking a tune is a little inconvenient. Using both the mouse and keyboard works, but my (personal) workflow would be much faster if we could press the keys matching the tone selector in the bottom: tap `a` to set the currently selected note to `a`, `z` for the "rest", `shift + C` for the higher C, and so on.

If needed, I'm open to creating a PR for it.

**Comment by walfie** [comment]
Thanks for the feature request!

I started working on a PR for this (#54). I still need to work through some build issues (seems some of the libraries are so outdated they don't build in CI anymore 😅 ), but I'll let you know once this is released.

**Comment by walfie** [comment]
This should be available now!

**Comment by Cezille07** [comment]
Awesome, I appreciate this! Thank you ✨
