### ISSUE TITLE
Add translations 

### ISSUE THREAD

**Issue by Lysoun** [walfie/ac-tune-maker#9]
Hello,

Would it be possible to make translations of the app possible? The English texts are not a problem but, since in my country notes are not named as in your app, it makes it really difficult for people not knowing the English convention to create tunes.

**Comment by walfie** [comment]
Sure, do you have a screenshot of what the notes look like in your version of the game, so I have an idea of what the differences are?

**Comment by Lysoun** [comment]
Of course, here you are: 

![French notes in ACNH](https://i.imgur.com/by41BrK.jpg)

**Comment by walfie** [comment]
Thanks! I will take a look at adding language options when I have some time later.

**Comment by walfie** [comment]
I've added it in #13 as an option in the modal:

![ac_tune_maker_lang_select](https://user-images.githubusercontent.com/11370525/80322426-0c37af00-87f3-11ea-9d8b-690001eb57a4.gif)
